### ISSUE TITLE
ModuleNotFoundError: No module named 'execjs' &

### ISSUE THREAD

**Issue by bing90508** [mepeichun/SubtitleTranslate#5]
Hi, I have already got pyexecjs {Requirement already satisfied: pyexecjs in ./Library/Python/3.7/lib/python/site-packages (1.5.1)} and jieba, but still return this error, could you help with this issue? TX

sharron.x@SharronsMacBook ~ % python3 sample.py   
If your target language is Chinese, please install third party library "jieba"
Traceback (most recent call last):
  File "/Users/sharron.x/sample.py", line 1, in <module>
    from utils import translate_and_compose
  File "/Users/sharron.x/utils.py", line 2, in <module>
    from util_trans import Translator
  File "/Users/sharron.x/util_trans.py", line 2, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

**Comment by GWDx** [comment]
pip install PyExecJS

**Comment by GWDx** [comment]
```bash
pip install PyExecJS
```
